// Generated by CoffeeScript 1.4.0
(function() {
  var s;

  window.StringScrambler = function(str) {
    var nameArr, origName, scramble, shuffleArray, swapTwoRandomArrayValues, _ref;
    nameArr = (_ref = str.split("")) != null ? _ref : [];
    origName = str != null ? str : "";
    swapTwoRandomArrayValues = function(array, i) {
      var j, tempi, tempj;
      j = Math.floor(Math.random() * (i + 1));
      tempi = array[i];
      tempj = array[j];
      array[i] = tempj;
      return array[j] = tempi;
    };
    shuffleArray = function(myArray) {
      var i, _results;
      i = myArray.length;
      if (i === 0) {
        return false;
      }
      _results = [];
      while (--i) {
        _results.push(swapTwoRandomArrayValues(myArray, i));
      }
      return _results;
    };
    scramble = function() {
      shuffleArray(nameArr);
      return nameArr.join("");
    };
    return {
      scramble: scramble
    };
  };

  s = StringScrambler("rodolphe");

  console.log(s.scramble());

}).call(this);
