// Generated by CoffeeScript 1.4.0
(function() {

  window.StringScrambler = function(str) {
    var dupHistory, history, nameArr, origName, scramble, shuffleArray, swapTwoRandomArrayValues, _ref;
    nameArr = (_ref = str.split("")) != null ? _ref : [];
    origName = str != null ? str : "";
    history = [str];
    swapTwoRandomArrayValues = function(array, i) {
      var j, tempi, tempj;
      j = Math.floor(Math.random() * (i + 1));
      tempi = array[i];
      tempj = array[j];
      array[i] = tempj;
      return array[j] = tempi;
    };
    shuffleArray = function(myArray) {
      var i, _results;
      i = myArray.length;
      if (i === 0) {
        return false;
      }
      _results = [];
      while (--i) {
        _results.push(swapTwoRandomArrayValues(myArray, i));
      }
      return _results;
    };
    scramble = function() {
      shuffleArray(nameArr);
      history.push(nameArr.join(""));
      return nameArr.join("");
    };
    dupHistory = function() {
      var locHistory, s, _i, _len;
      locHistory = [];
      for (_i = 0, _len = history.length; _i < _len; _i++) {
        s = history[_i];
        locHistory.push(s);
      }
      return locHistory;
    };
    return {
      getHistory: dupHistory,
      scramble: scramble
    };
  };

}).call(this);
